name: Build macOS

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -Coverflow-checks=y -Cdebug-assertions=y
  CARGO_INCREMENTAL: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rust_toolchain_version: ["1.81", "stable", "beta"]
        # OCaml 5 not supported on macOS yet
        ocaml_version: [4.14]
    runs-on: macos-latest
    name: Rust ${{ matrix.rust_toolchain_version }}, OCaml ${{ matrix.ocaml_version }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          rust_toolchain_version: ${{ matrix.rust_toolchain_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
